name: Simple EC2 SCP Deploy

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove sensitive and unnecessary files
      run: |
        mkdir clean-upload
        rsync -av --exclude='.git' --exclude='.github' --exclude='README.md' ./ clean-upload/

    - name: Upload to EC2 with SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "clean-upload/*"
        target: "/home/ubuntu/app"
        rm: false
        overwrite: true
