name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare upload folder (exclude .git and .github)
      run: |
        mkdir filtered
        rsync -av --exclude='.git' --exclude='.github' --exclude='README.md' ./ filtered/

    - name: Upload filtered files to EC2 via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "filtered/*"
        target: "/home/ubuntu/app"
